# Generated by Django 5.2.7 on 2025-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users_profile",
            },
        ),
    ]
