# Generated by Django 5.2.7 on 2025-11-05 06:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_weight_kg", models.FloatField(blank=True, null=True)),
                ("target_calories", models.IntegerField(blank=True, null=True)),
                ("consumed_calories", models.FloatField(default=0)),
                (
                    "reset_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("none", "No automatic reset"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.goal",
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom name, e.g. 'Post-workout lunch' or 'Sunday dinner'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.meals",
            },
        ),
        migrations.CreateModel(
            name="EatenMeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("eaten_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eaten_meals",
                        to="users.profile",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        db_column="meal_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eaten_instances",
                        to="core.meal",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.eaten_meal",
            },
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Canonical internal code, e.g. 'energy_kj', 'protein', 'sugars'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Energy (kJ)', 'Protein'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "g"),
                            ("mg", "mg"),
                            ("µg", "µg"),
                            ("kJ", "kJ"),
                            ("kcal", "kcal"),
                            ("%", "%"),
                            ("per_serving", "per_serving"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("macronutrient", "Macronutrient"),
                            ("vitamin", "Vitamin"),
                            ("mineral", "Mineral"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bitebuilder.nutrients",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="bitebuilder_categor_1f719a_idx"
                    ),
                    models.Index(fields=["code"], name="bitebuilder_code_9e7535_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoalNutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_amount",
                    models.FloatField(
                        help_text="Target amount per period (unit of nutrient)"
                    ),
                ),
                (
                    "consumed_amount",
                    models.FloatField(
                        default=0, help_text="Consumed amount so far in same unit"
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        db_column="goal_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_nutrients",
                        to="core.goal",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        db_column="nutrient_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_goals",
                        to="core.nutrient",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.goal_nutrient",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price_current",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_was",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_on_special", models.BooleanField(default=False)),
                (
                    "cup_price_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "cup_price_unit",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("product_url", models.URLField(blank=True, null=True)),
                ("health_star", models.CharField(blank=True, max_length=10, null=True)),
                ("allergens", models.TextField(blank=True, null=True)),
                (
                    "serving_size_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "serving_size_unit",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                (
                    "servings_per_pack",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "nutrition_basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per_100g", "per_100g"),
                            ("per_serving", "per_serving"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "primary_source",
                    models.CharField(
                        choices=[
                            ("woolworths", "Woolworths"),
                            ("openfoodfacts", "OpenFoodFacts"),
                            ("user_added", "User Added"),
                        ],
                        default="woolworths",
                        max_length=32,
                    ),
                ),
                ("last_enriched_at", models.DateTimeField(blank=True, null=True)),
                ("enrichment_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["barcode"], name="core_produc_barcode_5cc7aa_idx"
                    ),
                    models.Index(fields=["name"], name="core_produc_name_be3252_idx"),
                    models.Index(fields=["brand"], name="core_produc_brand_a4ba54_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        help_text="Amount eaten in product's unit (e.g., grams)"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        db_column="meal_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.meal",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_barcode",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_items",
                        to="core.product",
                        to_field="barcode",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.meal_item",
            },
        ),
        migrations.CreateModel(
            name="ProductNutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_per_100g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Amount per 100g or 100mL, depending on product basis.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "amount_per_serving",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_products",
                        to="core.nutrient",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_nutrients",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.product_nutrient",
            },
        ),
        migrations.CreateModel(
            name="SavedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="core.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_products",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "db_table": "bitebuilder.saved_product",
            },
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "date_time"], name="bitebuilder_user_id_0ee4ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["user", "meal_type", "date_time"],
                name="bitebuilder_user_id_138243_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eatenmeal",
            index=models.Index(
                fields=["user", "eaten_at"], name="bitebuilder_user_id_22afb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goalnutrient",
            index=models.Index(fields=["goal"], name="bitebuilder_goal_id_0ebe38_idx"),
        ),
        migrations.AddIndex(
            model_name="goalnutrient",
            index=models.Index(
                fields=["nutrient"], name="bitebuilder_nutrien_02992f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="goalnutrient",
            unique_together={("goal", "nutrient")},
        ),
        migrations.AddIndex(
            model_name="mealitem",
            index=models.Index(fields=["meal"], name="bitebuilder_meal_id_1db2cd_idx"),
        ),
        migrations.AddIndex(
            model_name="mealitem",
            index=models.Index(
                fields=["product"], name="bitebuilder_product_365ab1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productnutrient",
            index=models.Index(
                fields=["product", "nutrient"], name="bitebuilder_product_0ef31f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productnutrient",
            index=models.Index(
                fields=["nutrient"], name="bitebuilder_nutrien_386248_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productnutrient",
            unique_together={("product", "nutrient")},
        ),
        migrations.AddIndex(
            model_name="savedproduct",
            index=models.Index(fields=["user"], name="bitebuilder_user_id_da3a59_idx"),
        ),
        migrations.AddIndex(
            model_name="savedproduct",
            index=models.Index(
                fields=["product"], name="bitebuilder_product_fc2ded_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedproduct",
            unique_together={("user", "product")},
        ),
    ]
